[package]
name = "scuttleraft"
version = "0.1.0"
edition = "2021"

[dependencies]
fxhash = "0.2.1"
getrandom = "0.2.15"
indexmap = "2.2.6"
oorandom = "11.1.3"

[dev-dependencies]
mock_instant = "0.5.1"
